= GHR
Barrett Ray <barrettrjay@protonmail.com>
v0.0, 2024-10-13

A global hardware report, intended to allow anyone to gain insight into computer hardware.

== Layout

This is a bit of a monorepo. It includes everything related to GHR, including the website and surrounding tools.

Let's review the major files/directories:

* `Cargo.toml`: makes this into a Rust workspace.
* `libghr`: the Rust library that creates reports.
* `shared`: currently just exports the `libghr::Report` type for use in TypeScript.
* `frontend`: the website's frontend (viewable parts), written in React.
* `backend`: the website's backend (server stuff), made in Rust.

== Usage

Currently, there are no formal CLI/GUI tools to generate reports. However, you can head into link:./libghr/[`libghr`] and check out the examples to get something now.

== License

All source files in the GHR project are licensed under the Mozilla Public License 2.0. For additional information, see the link:./LICENSE[project license].

== Contributing

Outside contributions are welcomed! If you're making a bug fix, please feel free to pop in whenever. However, feature contributions (like new hardware) should be discussed before implementation. Please make an issue in that case.

In addition, please ensure your commits use https://www.conventionalcommits.org/en/v1.0.0[Conventional Commits] style and that any changes uphold semantic versioning. (e.g., `#[non_exhaustive]` on public types, etc.)