set windows-shell := ["C:\\Program Files\\Git\\bin\\sh.exe","-c"] 

pre_push: check
    clippy-tracing --action check

# runs cargo check for windows and linux (x86_64).
#
# assumes targets are installed.
check:
    cargo check --target x86_64-pc-windows-msvc
    cargo check --target x86_64-unknown-linux-gnu

# attempts to `cargo check` for all supported targets
check_all: _install_targets
    cargo check --target x86_64-pc-windows-msvc
    cargo check --target x86_64-unknown-linux-musl
    cargo check --target i686-pc-windows-msvc
    cargo check --target aarch64-unknown-linux-musl
    cargo check --target x86_64-unknown-linux-gnu
    cargo check --target riscv64gc-unknown-linux-gnu

_install_targets:
    rustup target add x86_64-pc-windows-msvc
    rustup target add x86_64-unknown-linux-musl
    rustup target add i686-pc-windows-msvc
    rustup target add aarch64-unknown-linux-musl
    rustup target add x86_64-unknown-linux-gnu
    rustup target add riscv64gc-unknown-linux-gnu

